#ifndef COLONY_CONFIG_H_
#define COLONY_CONFIG_H_

/// Enable SIMULATED Time
#define USE_CPL_SYSTEM_SIM_TICK

#define USE_CPL_SYSTEM_TRACE

#define OPTION_CPL_TSHELL_PROCESSOR_INPUT_SIZE      (4*1024)
#define OPTION_CPL_TSHELL_PROCESSOR_OUTPUT_SIZE     (4*1024)


#endif
